workflows:
  android-apk-workflow:
    name: Android APK Workflow (Free Tier)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.goldapp.daily_routine"
        APP_NAME: "Gold App"
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Generate Hive adapters
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs || true
      - name: Flutter analyze
        script: |
          flutter analyze || true
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

