import 'package:hive_flutter/hive_flutter.dart';
import '../models/routine_item.dart';
import '../models/custom_routine_template.dart';
import '../models/meal.dart';
import '../models/custom_meal_type.dart';
import '../models/water_intake.dart';
import '../models/self_care.dart';
import '../models/schedule_item.dart';
import '../models/calendar_event.dart';
import '../models/progress_data.dart';
import '../utils/constants.dart';

class DatabaseService {
  static DatabaseService? _instance;
  static DatabaseService get instance {
    _instance ??= DatabaseService._();
    return _instance!;
  }

  DatabaseService._();

  Box<RoutineItem>? _routinesBox;
  Box<CustomRoutineTemplate>? _customRoutineTemplatesBox;
  Box<Meal>? _mealsBox;
  Box<CustomMealType>? _customMealTypesBox;
  Box<WaterIntake>? _waterBox;
  Box<SelfCare>? _selfCareBox;
  Box<ScheduleItem>? _scheduleBox;
  Box<CalendarEvent>? _calendarEventsBox;
  Box<ProgressData>? _progressBox;
  Box? _settingsBox;

  Future<void> init() async {
    // Register adapters (will be generated by build_runner)
    // Hive.registerAdapter(RoutineItemAdapter());
    // Hive.registerAdapter(CustomRoutineTemplateAdapter());
    // Hive.registerAdapter(MealAdapter());
    // Hive.registerAdapter(CustomMealTypeAdapter());
    // Hive.registerAdapter(WaterIntakeAdapter());
    // Hive.registerAdapter(SelfCareAdapter());
    // Hive.registerAdapter(SelfCareStepAdapter());
    // Hive.registerAdapter(ScheduleItemAdapter());
    // Hive.registerAdapter(CalendarEventAdapter());
    // Hive.registerAdapter(ProgressDataAdapter());

    // Open boxes
    _routinesBox = await Hive.openBox<RoutineItem>(AppConstants.routinesBox);
    _customRoutineTemplatesBox = await Hive.openBox<CustomRoutineTemplate>(
        AppConstants.customRoutineTemplatesBox);
    _mealsBox = await Hive.openBox<Meal>(AppConstants.mealsBox);
    _customMealTypesBox =
        await Hive.openBox<CustomMealType>(AppConstants.customMealTypesBox);
    _waterBox = await Hive.openBox<WaterIntake>(AppConstants.waterBox);
    _selfCareBox = await Hive.openBox<SelfCare>(AppConstants.selfCareBox);
    _scheduleBox = await Hive.openBox<ScheduleItem>(AppConstants.scheduleBox);
    _calendarEventsBox =
        await Hive.openBox<CalendarEvent>(AppConstants.calendarEventsBox);
    _progressBox =
        await Hive.openBox<ProgressData>(AppConstants.progressBox);
    _settingsBox = await Hive.openBox(AppConstants.settingsBox);
  }

  // Routines
  Box<RoutineItem> get routinesBox => _routinesBox!;
  Box<CustomRoutineTemplate> get customRoutineTemplatesBox =>
      _customRoutineTemplatesBox!;

  // Meals
  Box<Meal> get mealsBox => _mealsBox!;
  Box<CustomMealType> get customMealTypesBox => _customMealTypesBox!;

  // Water
  Box<WaterIntake> get waterBox => _waterBox!;

  // Self-care
  Box<SelfCare> get selfCareBox => _selfCareBox!;

  // Schedule
  Box<ScheduleItem> get scheduleBox => _scheduleBox!;

  // Calendar
  Box<CalendarEvent> get calendarEventsBox => _calendarEventsBox!;

  // Progress
  Box<ProgressData> get progressBox => _progressBox!;

  // Settings
  Box get settingsBox => _settingsBox!;

  Future<void> clearAll() async {
    await _routinesBox?.clear();
    await _customRoutineTemplatesBox?.clear();
    await _mealsBox?.clear();
    await _customMealTypesBox?.clear();
    await _waterBox?.clear();
    await _selfCareBox?.clear();
    await _scheduleBox?.clear();
    await _calendarEventsBox?.clear();
    await _progressBox?.clear();
    await _settingsBox?.clear();
  }
}

